#! /bin/sh

if [ -z "$2" ]
then
	exec_count=2
else
	exec_count=$2
fi

if [ "$1" = "-h" ]
then
	echo "Usage: exe_file commande [nombre d'executions]"
	exit
fi

for proc in $(seq 0 $exec_count)
do
	$1 &
done
